name: phrase-matcher
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - fastapi
  - uvicorn
  - gensim
  - numpy
  - pandas
  - scikit-learn
  - nltk
  - fuzzywuzzy
  - python-levenshtein
  - jinja2
  - pytest
